sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer config github-oauth.github.com ${GH_TOKEN}
  - composer selfupdate
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls

notifications:
  email: matthiasnoback@gmail.com
