sudo: false

language: php

php:
  - 7.2
  - 7.3
  - 7.4

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls

notifications:
  email: matthiasnoback@gmail.com
